# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=b'Z\"github.com/bluegamez/space-fox/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63ontroller.proto\x12\x08protobuf\"\xed\x01\n\x06\x41\x63tion\x12\x14\n\x0c\x63ontrollerId\x18\x01 \x01(\t\x12\'\n\x06\x62utton\x18\x02 \x01(\x0e\x32\x17.protobuf.Action.Button\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.protobuf.Action.Type\"1\n\x06\x42utton\x12\x12\n\x0eUNKNOWN_BUTTON\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\"L\n\x04Type\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x10\n\x0cSINGLE_CLICK\x10\x01\x12\x10\n\x0c\x44OUBLE_CLICK\x10\x02\x12\x0e\n\nLONG_PRESS\x10\x03\"\r\n\x0b\x45ndOfStream2L\n\x08SpaceFox\x12@\n\x11\x43ontrollerActions\x12\x10.protobuf.Action\x1a\x15.protobuf.EndOfStream\"\x00(\x01\x42$Z\"github.com/bluegamez/space-fox/apib\x06proto3'
)



_ACTION_BUTTON = _descriptor.EnumDescriptor(
  name='Button',
  full_name='protobuf.Action.Button',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_BUTTON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=141,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_ACTION_BUTTON)

_ACTION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='protobuf.Action.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SINGLE_CLICK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE_CLICK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LONG_PRESS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=192,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_ACTION_TYPE)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='protobuf.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='controllerId', full_name='protobuf.Action.controllerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='button', full_name='protobuf.Action.button', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.Action.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_BUTTON,
    _ACTION_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=268,
)


_ENDOFSTREAM = _descriptor.Descriptor(
  name='EndOfStream',
  full_name='protobuf.EndOfStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=283,
)

_ACTION.fields_by_name['button'].enum_type = _ACTION_BUTTON
_ACTION.fields_by_name['type'].enum_type = _ACTION_TYPE
_ACTION_BUTTON.containing_type = _ACTION
_ACTION_TYPE.containing_type = _ACTION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['EndOfStream'] = _ENDOFSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Action)
  })
_sym_db.RegisterMessage(Action)

EndOfStream = _reflection.GeneratedProtocolMessageType('EndOfStream', (_message.Message,), {
  'DESCRIPTOR' : _ENDOFSTREAM,
  '__module__' : 'controller_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.EndOfStream)
  })
_sym_db.RegisterMessage(EndOfStream)


DESCRIPTOR._options = None

_SPACEFOX = _descriptor.ServiceDescriptor(
  name='SpaceFox',
  full_name='protobuf.SpaceFox',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=285,
  serialized_end=361,
  methods=[
  _descriptor.MethodDescriptor(
    name='ControllerActions',
    full_name='protobuf.SpaceFox.ControllerActions',
    index=0,
    containing_service=None,
    input_type=_ACTION,
    output_type=_ENDOFSTREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPACEFOX)

DESCRIPTOR.services_by_name['SpaceFox'] = _SPACEFOX

# @@protoc_insertion_point(module_scope)
