# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import controller_pb2 as controller__pb2


class SpaceFoxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ControllerActions = channel.stream_unary(
                '/protobuf.SpaceFox/ControllerActions',
                request_serializer=controller__pb2.Action.SerializeToString,
                response_deserializer=controller__pb2.EndOfStream.FromString,
                )


class SpaceFoxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ControllerActions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceFoxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ControllerActions': grpc.stream_unary_rpc_method_handler(
                    servicer.ControllerActions,
                    request_deserializer=controller__pb2.Action.FromString,
                    response_serializer=controller__pb2.EndOfStream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.SpaceFox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpaceFox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ControllerActions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/protobuf.SpaceFox/ControllerActions',
            controller__pb2.Action.SerializeToString,
            controller__pb2.EndOfStream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
